### ISSUE TITLE
Which modifiers are allowed? 

### ISSUE THREAD

**Issue by furesoft** [10usb/assembler#3]

**Comment by 10usb** [comment]
At the moment the regex pattern allows any of the following characters +-&!*?$%=~} 

It also allowed to have multiple characters in any combination, though I would not recommend very long ones when mixing.

There's also a special modifier (that I haven't documented yet 🙈) that exists within the context of a macro $& which passes the modifier that was applied in calling it. Mostly useful in a language file. In the example R322 it's even chained. Where the "call" macro passes the optional modifier to the "push" and "jmp" instructions, and these passes it on to "mov" that passes it on to "instr" macro that makes the decision depending on the actual modifier which bit to set.


Hope this helps answer your question

**Comment by furesoft** [comment]
Yes thanks
