### ISSUE TITLE
Align Instructions

### ISSUE THREAD

**Issue by furesoft** [10usb/assembler#6]
I am currently workin on an implementation for a platform that needs the instruction to be right aligned. How could I align instructions and arguments?

**Comment by 10usb** [comment]
At the moment it can not be done. The support for build-in $ variables for offset and origin still need to be implemented. And maybe it works by setting these in the base interpreter before the processing of each instruction. But I've haven't tested that yet.

In theory if these work a macro like this could do the trick
```
macro align divider {
  local x = ($ % divider )
  if (x >= 3){
    db 0
  }
  if (x >= 2){
    db 0
  }
  if (x >= 1){
    db 0
  }
}
```
