### ISSUE TITLE
Missing Values

### ISSUE THREAD

**Issue by furesoft** [10usb/assembler#7]
If I am using 0xFFFE only FE will be emitted

**Comment by 10usb** [comment]
The db instruction (data-byte) will only output a byte. To output a larger value you need to shift high byte 8 bits.

For little endian word you can use the macro below, and the same can be done to achieve a double word or a quad word.
```
macro dw v {
    db v
    db (v >> 8)
}
```

Note that internally a number is stored as a signed 64bit number so 0xFFFE most likely used as an unsigned 16bit number will not be equal to -2.
